data_ingestion:
  bucket_name : "rag-genai-p-2-data"
  content_file_name : "content_data.txt"
  urls :  [ 
            "https://en.wikipedia.org/wiki/Battle_of_Stalingrad",
            "https://en.wikipedia.org/wiki/Pacific_War",
            "https://en.wikipedia.org/wiki/Battle_of_Britain",
            "https://en.wikipedia.org/wiki/Aftermath_of_World_War_II",    
            "https://en.wikipedia.org/wiki/Outline_of_World_War_II",
            "https://en.wikipedia.org/wiki/Causes_of_World_War_II",
            "https://en.wikipedia.org/wiki/Military_history_of_the_United_States_during_World_War_II",
            "https://en.wikipedia.org/wiki/Winston_Churchill_in_the_Second_World_War"
            ]
embedding_model : 'all-MiniLM-L6-v2'
text_to_text_model : "google/long-t5-tglobal-base"

data_processing:
  chunk_size : 1000
  overlap_chunk_size : 300

data_retriever:
  top_k : 10

data_generator:
  top_k : 10
